name: 'Publish package'

on:
    push:
        tags:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v3

            - name: 'Set up JDK 17'
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: 'Build and Test'
              run: mvn verify

            - name: 'Publish package'
              run: mvn -Dmaven.test.skip=true deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
